"""
Nightly umpire profile updater.

Pulls fresh HP-game stats from the Umpire Scorecards API
(umpscorecards.com/api/umpires) and rewrites umpire_data.py
so the Zone Model always has current tendencies.

Runs automatically as part of the GitHub Actions daily workflow
(called from cron_entry.py before picks are scored).

Fallback: if the API is unreachable the existing file is left untouched.
"""

from __future__ import annotations
import json
import os
import sys
import textwrap
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

SCORECARDS_API = "https://umpscorecards.com/api/umpires"
THIS_DIR = Path(__file__).parent
UMPIRE_FILE = THIS_DIR / "umpire_data.py"

# League-average anchors (updated manually each off-season)
LEAGUE_AVG = {
    "runs_per_game_per_team": 4.43,
    "k_per_game": 8.9,
    "bb_per_game": 3.2,
    "total_avg": 9.1,
}


def _fetch_scorecards() -> list[dict]:
    """Fetch all umpire records from the Umpire Scorecards public API."""
    req = urllib.request.Request(
        SCORECARDS_API,
        headers={"User-Agent": "ZoneModel/1.0 (automated; contact alex.l.black.2008@gmail.com)"},
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read().decode())


def _map_to_profile(rec: dict) -> dict | None:
    """Convert a Umpire Scorecards record to our internal profile format."""
    games = rec.get("total_games") or rec.get("games") or 0
    if games < 50:
        return None

    # csraa: called_strike_rate_above_avg in percentage points
    csraa = round(float(rec.get("csraa") or rec.get("cs_above_avg") or 0.0), 2)

    # run_impact: run differential per game vs league average
    # Scorecards exposes "favor_home" and total run differentials; we derive
    # a simple per-game impact. Fall back to estimate from csraa if missing.
    run_impact = rec.get("run_impact") or rec.get("runs_above_avg")
    if run_impact is None:
        run_impact = round(-csraa * 0.23, 2)   # empirical coefficient
    else:
        run_impact = round(float(run_impact), 2)

    # k_factor / bb_factor derived from k_above_avg / bb_above_avg when present
    k_aa  = float(rec.get("k_above_avg")  or 0.0)
    bb_aa = float(rec.get("bb_above_avg") or 0.0)
    k_factor  = round(1.0 + k_aa  / LEAGUE_AVG["k_per_game"],  3)
    bb_factor = round(1.0 + bb_aa / LEAGUE_AVG["bb_per_game"], 3)

    return {
        "csraa":      csraa,
        "run_impact": run_impact,
        "k_factor":   k_factor,
        "bb_factor":  bb_factor,
        "games":      int(games),
    }


def _write_umpire_file(profiles: dict[str, dict], updated_at: str) -> None:
    """Overwrite umpire_data.py with the refreshed profiles."""
    # Sort by run_impact descending (pitcher-friendly first)
    sorted_items = sorted(
        [(k, v) for k, v in profiles.items() if k != "__UNKNOWN__"],
        key=lambda x: -x[1]["csraa"],
    )

    lines = [
        '"""',
        "Umpire historical tendency profiles.",
        "",
        "Auto-generated by update_umpire_data.py — do not edit by hand.",
        f"Last refreshed: {updated_at}",
        "Source: umpscorecards.com/api/umpires (2021-2025 HP games, min 50 games)",
        "",
        "Key metrics:",
        "  csraa      - Called Strike Rate Above Average (percentage points)",
        "               Positive = bigger zone → pitcher-friendly",
        "  run_impact - Run delta per game vs league average (negative = fewer runs)",
        "  k_factor   - Strikeout multiplier (1.0 = neutral)",
        "  bb_factor  - Walk multiplier (1.0 = neutral)",
        "  games      - HP games in sample",
        '"""',
        "",
        "UMPIRE_PROFILES = {",
    ]

    for name, p in sorted_items:
        lines.append(
            f'    {json.dumps(name)}: '
            f'{{"csraa": {p["csraa"]:+.2f}, "run_impact": {p["run_impact"]:+.2f}, '
            f'"k_factor": {p["k_factor"]:.3f}, "bb_factor": {p["bb_factor"]:.3f}, '
            f'"games": {p["games"]}}},'
        )

    lines += [
        "    # Neutral baseline used when umpire is unknown",
        '    "__UNKNOWN__": {"csraa": 0.00, "run_impact": 0.00, "k_factor": 1.000, "bb_factor": 1.000, "games": 0},',
        "}",
        "",
        "# League-average context anchors (2024-2025 MLB seasons)",
        f"LEAGUE_AVG = {json.dumps(LEAGUE_AVG, indent=4)}",
        "",
    ]

    UMPIRE_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"  [Umpire updater] Wrote {len(sorted_items)} profiles → {UMPIRE_FILE.name}")


def run_update() -> bool:
    """
    Fetch latest umpire data and refresh umpire_data.py.
    Returns True on success, False if the API was unreachable.
    """
    print("  [Umpire updater] Fetching from umpscorecards.com …")
    try:
        raw = _fetch_scorecards()
    except (urllib.error.URLError, Exception) as e:
        print(f"  [Umpire updater] API unreachable ({e}) — keeping existing profiles.")
        return False

    profiles: dict[str, dict] = {}
    skipped = 0
    for rec in raw:
        name = (rec.get("name") or rec.get("umpire_name") or "").strip()
        if not name:
            continue
        profile = _map_to_profile(rec)
        if profile is None:
            skipped += 1
            continue
        # If the same name appears twice (e.g. with different year filters),
        # keep the one with more games.
        if name in profiles and profiles[name]["games"] >= profile["games"]:
            continue
        profiles[name] = profile

    if not profiles:
        print("  [Umpire updater] API returned no usable records — keeping existing profiles.")
        return False

    updated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    _write_umpire_file(profiles, updated_at)
    print(f"  [Umpire updater] Done. {len(profiles)} umpires updated, {skipped} skipped (<50 games).")
    return True


if __name__ == "__main__":
    success = run_update()
    sys.exit(0 if success else 1)
